### ISSUE TITLE
[Feature Request] NWA support?

### ISSUE THREAD

**Issue by ShneekeyTheLost** [alttpo/sni#17] opened 2022-07-17 20:25 UTC
So, BizHawk's LUA implementation in Linux is... well, it has problems finding the appropriate path and cpath for the lua-socket module. Someone wrote an External Tool which implements a link to QUSB via NWA instead of LUA. 

However, I prefer SNI's implementation, as well as the native linux releases so I don't have to constantly compile QUSB every time it releases. Would it be possible to implement NWA support?

**Comment by JamesDunne** [comment] 2022-07-17 21:49
Skars wrote the BizHawk external tool. Yup NWA is already supported in SNI but needs testing as I think the NWA protocol has evolved slightly beyond when SNI originally implemented it.

**Comment by ShneekeyTheLost** [comment] 2022-07-18 01:47
Well, when I tried using it with SNI, it kept disconnecting and attempting to reconnect. However, there may be something I have to enable with SNI? There doesn't seem to be a config file in home/.sni folder and the apps.yaml file doesn't reference NWA that I can discern.

**Comment by JamesDunne** [comment] 2022-07-18 01:53
i don't think there's anything to do as an end user. as i mentioned before, the nwa protocol evolved slightly so I just need to update the nwa handling code per the latest version.

**Comment by JamesDunne** [comment] 2022-07-26 01:54
Okay I got this working in main, pushing out a release build now.

**Comment by ShneekeyTheLost** [comment] 2022-07-27 06:20
NWA now connects to SNI but not to AP. Will have to explore further on my end.

**Comment by JamesDunne** [comment] 2022-09-09 01:01
Closing this unless there's further info to demonstrate an issue

**Closed by JamesDunne** 2022-09-09 01:01 UTC

**Comment by ShneekeyTheLost** [comment] 2022-09-28 02:22
Additional information on this issue:

Attempting to connect to SNI via NWA results in the following being spammed:

Connecting to SNI at ws://localhost:23074 ...
Connecting to SNI at ws://localhost:23074 ...
Attaching to emunwa://127.0.0.1:48881
Attached to emunwa://127.0.0.1:48881
Lost connection to the snes, type /snes to reconnect
...reconnecting in 5s

Not sure what is causing this or where the issue is. I am using the second beta of the NWA tool from Bizhawk

**Comment by JimDunne** [comment] 2022-09-28 03:29
Discovered the issue is with the bizhawk bsnes v115 core's libsnes target. The libsnes defines memory "regions" which the NWA External Tool translates to NWA memory domain names, except bsnes uses names like `CARTRIDGE_ROM` where NWA expects `CARTROM`. This needs translating in the NWA External Tool because SNI already uses the `CARTROM` which works for the bizhawk snes9x core.

**Comment by JamesDunne** [comment] 2022-09-28 03:30
Discovered the issue is with the bizhawk bsnes v115 core's libsnes target. The libsnes defines memory "regions" which the NWA External Tool translates to NWA memory domain names, except bsnes uses names like `CARTRIDGE_ROM` where NWA expects `CARTROM`. This needs translating in the NWA External Tool because SNI already uses the `CARTROM` which works for the bizhawk snes9x core.
